/* tslint:disable */
/* eslint-disable */
/**
 * WI API
 * API für Verwaltung von Personen, Dozenten, Studierenden, Forschungen, Modulen und Kursen
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the GetLecturers200ResponseInner interface.
 */
export function instanceOfGetLecturers200ResponseInner(value) {
  return true;
}
export function GetLecturers200ResponseInnerFromJSON(json) {
  return GetLecturers200ResponseInnerFromJSONTyped(json, false);
}
export function GetLecturers200ResponseInnerFromJSONTyped(
  json,
  ignoreDiscriminator,
) {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    title: json["Title"] == null ? undefined : json["Title"],
    firstname: json["Firstname"] == null ? undefined : json["Firstname"],
    lastname: json["Lastname"] == null ? undefined : json["Lastname"],
    gender: json["Gender"] == null ? undefined : json["Gender"],
    salutationShort:
      json["Salutation_short"] == null ? undefined : json["Salutation_short"],
    salutationFull:
      json["Salutation_full"] == null ? undefined : json["Salutation_full"],
    roleNow: json["RoleNow"] == null ? undefined : json["RoleNow"],
    personnelId: json["PersonnelId"] == null ? undefined : json["PersonnelId"],
  };
}
export function GetLecturers200ResponseInnerToJSON(json) {
  return GetLecturers200ResponseInnerToJSONTyped(json, false);
}
export function GetLecturers200ResponseInnerToJSONTyped(
  value,
  ignoreDiscriminator = false,
) {
  if (value == null) {
    return value;
  }
  return {
    id: value["id"],
    Title: value["title"],
    Firstname: value["firstname"],
    Lastname: value["lastname"],
    Gender: value["gender"],
    Salutation_short: value["salutationShort"],
    Salutation_full: value["salutationFull"],
    RoleNow: value["roleNow"],
    PersonnelId: value["personnelId"],
  };
}
