/* tslint:disable */
/* eslint-disable */
/**
 * WI API
 * API für Verwaltung von Personen, Dozenten, Studierenden, Forschungen, Modulen und Kursen
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the GetModuleUnits200ResponseInner interface.
 */
export function instanceOfGetModuleUnits200ResponseInner(value) {
  return true;
}
export function GetModuleUnits200ResponseInnerFromJSON(json) {
  return GetModuleUnits200ResponseInnerFromJSONTyped(json, false);
}
export function GetModuleUnits200ResponseInnerFromJSONTyped(
  json,
  ignoreDiscriminator,
) {
  if (json == null) {
    return json;
  }
  return {
    moduleNr: json["ModuleNr"] == null ? undefined : json["ModuleNr"],
    unitNr: json["UnitNr"] == null ? undefined : json["UnitNr"],
    unitName: json["UnitName"] == null ? undefined : json["UnitName"],
    units: json["Units"] == null ? undefined : json["Units"],
    moduleName: json["ModuleName"] == null ? undefined : json["ModuleName"],
    credits: json["Credits"] == null ? undefined : json["Credits"],
  };
}
export function GetModuleUnits200ResponseInnerToJSON(json) {
  return GetModuleUnits200ResponseInnerToJSONTyped(json, false);
}
export function GetModuleUnits200ResponseInnerToJSONTyped(
  value,
  ignoreDiscriminator = false,
) {
  if (value == null) {
    return value;
  }
  return {
    ModuleNr: value["moduleNr"],
    UnitNr: value["unitNr"],
    UnitName: value["unitName"],
    Units: value["units"],
    ModuleName: value["moduleName"],
    Credits: value["credits"],
  };
}
