/* tslint:disable */
/* eslint-disable */
/**
 * WI API
 * API für Verwaltung von Personen, Dozenten, Studierenden, Forschungen, Modulen und Kursen
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the GetModuleLecturers200ResponseInner interface.
 */
export function instanceOfGetModuleLecturers200ResponseInner(value) {
  return true;
}
export function GetModuleLecturers200ResponseInnerFromJSON(json) {
  return GetModuleLecturers200ResponseInnerFromJSONTyped(json, false);
}
export function GetModuleLecturers200ResponseInnerFromJSONTyped(
  json,
  ignoreDiscriminator,
) {
  if (json == null) {
    return json;
  }
  return {
    firstname: json["Firstname"] == null ? undefined : json["Firstname"],
    lastname: json["Lastname"] == null ? undefined : json["Lastname"],
    moduleNr: json["ModuleNr"] == null ? undefined : json["ModuleNr"],
    unitName: json["UnitName"] == null ? undefined : json["UnitName"],
    unitNr: json["UnitNr"] == null ? undefined : json["UnitNr"],
    semestername:
      json["Semestername"] == null ? undefined : json["Semestername"],
    courseNr: json["CourseNr"] == null ? undefined : json["CourseNr"],
  };
}
export function GetModuleLecturers200ResponseInnerToJSON(json) {
  return GetModuleLecturers200ResponseInnerToJSONTyped(json, false);
}
export function GetModuleLecturers200ResponseInnerToJSONTyped(
  value,
  ignoreDiscriminator = false,
) {
  if (value == null) {
    return value;
  }
  return {
    Firstname: value["firstname"],
    Lastname: value["lastname"],
    ModuleNr: value["moduleNr"],
    UnitName: value["unitName"],
    UnitNr: value["unitNr"],
    Semestername: value["semestername"],
    CourseNr: value["courseNr"],
  };
}
