/* tslint:disable */
/* eslint-disable */
/**
 * WI API
 * API für Verwaltung von Personen, Dozenten, Studierenden, Forschungen, Modulen und Kursen
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the GetResearchMathWished200ResponseInner interface.
 */
export function instanceOfGetResearchMathWished200ResponseInner(value) {
  return true;
}
export function GetResearchMathWished200ResponseInnerFromJSON(json) {
  return GetResearchMathWished200ResponseInnerFromJSONTyped(json, false);
}
export function GetResearchMathWished200ResponseInnerFromJSONTyped(
  json,
  ignoreDiscriminator,
) {
  if (json == null) {
    return json;
  }
  return {
    researchId: json["ResearchId"] == null ? undefined : json["ResearchId"],
    matchWishLast:
      json["MatchWishLast"] == null ? undefined : json["MatchWishLast"],
    matchWishFirst:
      json["MatchWishFirst"] == null ? undefined : json["MatchWishFirst"],
    matchWishId: json["MatchWishId"] == null ? undefined : json["MatchWishId"],
    personFromId:
      json["PersonFromId"] == null ? undefined : json["PersonFromId"],
    personnelWhoId:
      json["PersonnelWhoId"] == null ? undefined : json["PersonnelWhoId"],
    priority: json["Priority"] == null ? undefined : json["Priority"],
    _true: json["true"] == null ? undefined : json["true"],
    matchWisherLast:
      json["MatchWisherLast"] == null ? undefined : json["MatchWisherLast"],
    matchWisherFirst:
      json["MatchWisherFirst"] == null ? undefined : json["MatchWisherFirst"],
  };
}
export function GetResearchMathWished200ResponseInnerToJSON(json) {
  return GetResearchMathWished200ResponseInnerToJSONTyped(json, false);
}
export function GetResearchMathWished200ResponseInnerToJSONTyped(
  value,
  ignoreDiscriminator = false,
) {
  if (value == null) {
    return value;
  }
  return {
    ResearchId: value["researchId"],
    MatchWishLast: value["matchWishLast"],
    MatchWishFirst: value["matchWishFirst"],
    MatchWishId: value["matchWishId"],
    PersonFromId: value["personFromId"],
    PersonnelWhoId: value["personnelWhoId"],
    Priority: value["priority"],
    true: value["_true"],
    MatchWisherLast: value["matchWisherLast"],
    MatchWisherFirst: value["matchWisherFirst"],
  };
}
