/* tslint:disable */
/* eslint-disable */
/**
 * WI API
 * API für Verwaltung von Personen, Dozenten, Studierenden, Forschungen, Modulen und Kursen
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the GetResearches200ResponseInner interface.
 */
export function instanceOfGetResearches200ResponseInner(value) {
  return true;
}
export function GetResearches200ResponseInnerFromJSON(json) {
  return GetResearches200ResponseInnerFromJSONTyped(json, false);
}
export function GetResearches200ResponseInnerFromJSONTyped(
  json,
  ignoreDiscriminator,
) {
  if (json == null) {
    return json;
  }
  return {
    researchId: json["ResearchId"] == null ? undefined : json["ResearchId"],
    title: json["Title"] == null ? undefined : json["Title"],
    personnelId: json["PersonnelId"] == null ? undefined : json["PersonnelId"],
    unitName: json["UnitName"] == null ? undefined : json["UnitName"],
    matriNr: json["MatriNr"] == null ? undefined : json["MatriNr"],
    studentPersonId:
      json["StudentPersonId"] == null ? undefined : json["StudentPersonId"],
    studentFirst:
      json["StudentFirst"] == null ? undefined : json["StudentFirst"],
    studentLast: json["StudentLast"] == null ? undefined : json["StudentLast"],
    courseNr: json["CourseNr"] == null ? undefined : json["CourseNr"],
    problem: json["Problem"] == null ? undefined : json["Problem"],
    methodology: json["Methodology"] == null ? undefined : json["Methodology"],
    goal: json["Goal"] == null ? undefined : json["Goal"],
  };
}
export function GetResearches200ResponseInnerToJSON(json) {
  return GetResearches200ResponseInnerToJSONTyped(json, false);
}
export function GetResearches200ResponseInnerToJSONTyped(
  value,
  ignoreDiscriminator = false,
) {
  if (value == null) {
    return value;
  }
  return {
    ResearchId: value["researchId"],
    Title: value["title"],
    PersonnelId: value["personnelId"],
    UnitName: value["unitName"],
    MatriNr: value["matriNr"],
    StudentPersonId: value["studentPersonId"],
    StudentFirst: value["studentFirst"],
    StudentLast: value["studentLast"],
    CourseNr: value["courseNr"],
    Problem: value["problem"],
    Methodology: value["methodology"],
    Goal: value["goal"],
  };
}
