/* tslint:disable */
/* eslint-disable */
/**
 * WI API
 * API für Verwaltung von Personen, Dozenten, Studierenden, Forschungen, Modulen und Kursen
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the GetSemester200ResponseInner interface.
 */
export function instanceOfGetSemester200ResponseInner(value) {
  return true;
}
export function GetSemester200ResponseInnerFromJSON(json) {
  return GetSemester200ResponseInnerFromJSONTyped(json, false);
}
export function GetSemester200ResponseInnerFromJSONTyped(
  json,
  ignoreDiscriminator,
) {
  if (json == null) {
    return json;
  }
  return {
    name: json["Name"] == null ? undefined : json["Name"],
    nameShort: json["Name_short"] == null ? undefined : json["Name_short"],
    startDate:
      json["StartDate"] == null ? undefined : new Date(json["StartDate"]),
    endDate: json["EndDate"] == null ? undefined : new Date(json["EndDate"]),
    cycle: json["Cycle"] == null ? undefined : json["Cycle"],
    type: json["Type"] == null ? undefined : json["Type"],
  };
}
export function GetSemester200ResponseInnerToJSON(json) {
  return GetSemester200ResponseInnerToJSONTyped(json, false);
}
export function GetSemester200ResponseInnerToJSONTyped(
  value,
  ignoreDiscriminator = false,
) {
  if (value == null) {
    return value;
  }
  return {
    Name: value["name"],
    Name_short: value["nameShort"],
    StartDate:
      value["startDate"] == null
        ? value["startDate"]
        : value["startDate"].toISOString().substring(0, 10),
    EndDate:
      value["endDate"] == null
        ? value["endDate"]
        : value["endDate"].toISOString().substring(0, 10),
    Cycle: value["cycle"],
    Type: value["type"],
  };
}
