/* tslint:disable */
/* eslint-disable */
/**
 * WI API
 * API für Verwaltung von Personen, Dozenten, Studierenden, Forschungen, Modulen und Kursen
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __awaiter =
  (this && this.__awaiter) ||
  function (thisArg, _arguments, P, generator) {
    function adopt(value) {
      return value instanceof P
        ? value
        : new P(function (resolve) {
            resolve(value);
          });
    }
    return new (P || (P = Promise))(function (resolve, reject) {
      function fulfilled(value) {
        try {
          step(generator.next(value));
        } catch (e) {
          reject(e);
        }
      }
      function rejected(value) {
        try {
          step(generator["throw"](value));
        } catch (e) {
          reject(e);
        }
      }
      function step(result) {
        result.done
          ? resolve(result.value)
          : adopt(result.value).then(fulfilled, rejected);
      }
      step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
  };
import * as runtime from "../runtime.js";
import {
  GetCourses200ResponseInnerFromJSON,
  GetModuleLecturers200ResponseInnerFromJSON,
  GetModuleUnits200ResponseInnerFromJSON,
  GetResearchMathWished200ResponseInnerFromJSON,
  GetResearches200ResponseInnerFromJSON,
} from "../models/index.js";
/**
 *
 */
export class LecturesApi extends runtime.BaseAPI {
  /**
   * Liste der kurse zu einem datum
   */
  getCoursesRaw(requestParameters, initOverrides) {
    return __awaiter(this, void 0, void 0, function* () {
      if (requestParameters["date"] == null) {
        throw new runtime.RequiredError(
          "date",
          'Required parameter "date" was null or undefined when calling getCourses().',
        );
      }
      const queryParameters = {};
      const headerParameters = {};
      if (this.configuration && this.configuration.apiKey) {
        queryParameters["key"] = yield this.configuration.apiKey("key"); // ApiKeyAuth authentication
      }
      let urlPath = `/courses/{date}`;
      if (requestParameters["date"] instanceof Date) {
        urlPath = urlPath.replace(
          `{${"date"}}`,
          encodeURIComponent(
            requestParameters["date"].toISOString().substring(0, 10),
          ),
        );
      } else {
        urlPath = urlPath.replace(
          `{${"date"}}`,
          encodeURIComponent(String(requestParameters["date"])),
        );
      }
      const response = yield this.request(
        {
          path: urlPath,
          method: "GET",
          headers: headerParameters,
          query: queryParameters,
        },
        initOverrides,
      );
      return new runtime.JSONApiResponse(response, (jsonValue) =>
        jsonValue.map(GetCourses200ResponseInnerFromJSON),
      );
    });
  }
  /**
   * Liste der kurse zu einem datum
   */
  getCourses(requestParameters, initOverrides) {
    return __awaiter(this, void 0, void 0, function* () {
      const response = yield this.getCoursesRaw(
        requestParameters,
        initOverrides,
      );
      return yield response.value();
    });
  }
  /**
   * Dozenten zu moduleinheiten
   */
  getModuleLecturersRaw(initOverrides) {
    return __awaiter(this, void 0, void 0, function* () {
      const queryParameters = {};
      const headerParameters = {};
      if (this.configuration && this.configuration.apiKey) {
        queryParameters["key"] = yield this.configuration.apiKey("key"); // ApiKeyAuth authentication
      }
      let urlPath = `/module_lecturer`;
      const response = yield this.request(
        {
          path: urlPath,
          method: "GET",
          headers: headerParameters,
          query: queryParameters,
        },
        initOverrides,
      );
      return new runtime.JSONApiResponse(response, (jsonValue) =>
        jsonValue.map(GetModuleLecturers200ResponseInnerFromJSON),
      );
    });
  }
  /**
   * Dozenten zu moduleinheiten
   */
  getModuleLecturers(initOverrides) {
    return __awaiter(this, void 0, void 0, function* () {
      const response = yield this.getModuleLecturersRaw(initOverrides);
      return yield response.value();
    });
  }
  /**
   * Liste der moduleinheiten
   */
  getModuleUnitsRaw(initOverrides) {
    return __awaiter(this, void 0, void 0, function* () {
      const queryParameters = {};
      const headerParameters = {};
      if (this.configuration && this.configuration.apiKey) {
        queryParameters["key"] = yield this.configuration.apiKey("key"); // ApiKeyAuth authentication
      }
      let urlPath = `/module_units`;
      const response = yield this.request(
        {
          path: urlPath,
          method: "GET",
          headers: headerParameters,
          query: queryParameters,
        },
        initOverrides,
      );
      return new runtime.JSONApiResponse(response, (jsonValue) =>
        jsonValue.map(GetModuleUnits200ResponseInnerFromJSON),
      );
    });
  }
  /**
   * Liste der moduleinheiten
   */
  getModuleUnits(initOverrides) {
    return __awaiter(this, void 0, void 0, function* () {
      const response = yield this.getModuleUnitsRaw(initOverrides);
      return yield response.value();
    });
  }
  /**
   * Matchwishes für eine forschung
   */
  getResearchMathWishedRaw(requestParameters, initOverrides) {
    return __awaiter(this, void 0, void 0, function* () {
      if (requestParameters["researchId"] == null) {
        throw new runtime.RequiredError(
          "researchId",
          'Required parameter "researchId" was null or undefined when calling getResearchMathWished().',
        );
      }
      const queryParameters = {};
      const headerParameters = {};
      if (this.configuration && this.configuration.apiKey) {
        queryParameters["key"] = yield this.configuration.apiKey("key"); // ApiKeyAuth authentication
      }
      let urlPath = `/research-matchwishes/{researchId}`;
      urlPath = urlPath.replace(
        `{${"researchId"}}`,
        encodeURIComponent(String(requestParameters["researchId"])),
      );
      const response = yield this.request(
        {
          path: urlPath,
          method: "GET",
          headers: headerParameters,
          query: queryParameters,
        },
        initOverrides,
      );
      return new runtime.JSONApiResponse(response, (jsonValue) =>
        jsonValue.map(GetResearchMathWished200ResponseInnerFromJSON),
      );
    });
  }
  /**
   * Matchwishes für eine forschung
   */
  getResearchMathWished(requestParameters, initOverrides) {
    return __awaiter(this, void 0, void 0, function* () {
      const response = yield this.getResearchMathWishedRaw(
        requestParameters,
        initOverrides,
      );
      return yield response.value();
    });
  }
  /**
   * Forschungen ab einem datum
   */
  getResearchesRaw(requestParameters, initOverrides) {
    return __awaiter(this, void 0, void 0, function* () {
      if (requestParameters["date"] == null) {
        throw new runtime.RequiredError(
          "date",
          'Required parameter "date" was null or undefined when calling getResearches().',
        );
      }
      const queryParameters = {};
      const headerParameters = {};
      if (this.configuration && this.configuration.apiKey) {
        queryParameters["key"] = yield this.configuration.apiKey("key"); // ApiKeyAuth authentication
      }
      let urlPath = `/researches/{date}`;
      if (requestParameters["date"] instanceof Date) {
        urlPath = urlPath.replace(
          `{${"date"}}`,
          encodeURIComponent(
            requestParameters["date"].toISOString().substring(0, 10),
          ),
        );
      } else {
        urlPath = urlPath.replace(
          `{${"date"}}`,
          encodeURIComponent(String(requestParameters["date"])),
        );
      }
      const response = yield this.request(
        {
          path: urlPath,
          method: "GET",
          headers: headerParameters,
          query: queryParameters,
        },
        initOverrides,
      );
      return new runtime.JSONApiResponse(response, (jsonValue) =>
        jsonValue.map(GetResearches200ResponseInnerFromJSON),
      );
    });
  }
  /**
   * Forschungen ab einem datum
   */
  getResearches(requestParameters, initOverrides) {
    return __awaiter(this, void 0, void 0, function* () {
      const response = yield this.getResearchesRaw(
        requestParameters,
        initOverrides,
      );
      return yield response.value();
    });
  }
}
