/* tslint:disable */
/* eslint-disable */
/**
 * WI API
 * API für Verwaltung von Personen, Dozenten, Studierenden, Forschungen, Modulen und Kursen
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __awaiter =
  (this && this.__awaiter) ||
  function (thisArg, _arguments, P, generator) {
    function adopt(value) {
      return value instanceof P
        ? value
        : new P(function (resolve) {
            resolve(value);
          });
    }
    return new (P || (P = Promise))(function (resolve, reject) {
      function fulfilled(value) {
        try {
          step(generator.next(value));
        } catch (e) {
          reject(e);
        }
      }
      function rejected(value) {
        try {
          step(generator["throw"](value));
        } catch (e) {
          reject(e);
        }
      }
      function step(result) {
        result.done
          ? resolve(result.value)
          : adopt(result.value).then(fulfilled, rejected);
      }
      step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
  };
import * as runtime from "../runtime.js";
import { GetSemester200ResponseInnerFromJSON } from "../models/index.js";
/**
 *
 */
export class SemesterApi extends runtime.BaseAPI {
  /**
   * Liste aller semester
   */
  getSemesterRaw(initOverrides) {
    return __awaiter(this, void 0, void 0, function* () {
      const queryParameters = {};
      const headerParameters = {};
      if (this.configuration && this.configuration.apiKey) {
        queryParameters["key"] = yield this.configuration.apiKey("key"); // ApiKeyAuth authentication
      }
      let urlPath = `/semester`;
      const response = yield this.request(
        {
          path: urlPath,
          method: "GET",
          headers: headerParameters,
          query: queryParameters,
        },
        initOverrides,
      );
      return new runtime.JSONApiResponse(response, (jsonValue) =>
        jsonValue.map(GetSemester200ResponseInnerFromJSON),
      );
    });
  }
  /**
   * Liste aller semester
   */
  getSemester(initOverrides) {
    return __awaiter(this, void 0, void 0, function* () {
      const response = yield this.getSemesterRaw(initOverrides);
      return yield response.value();
    });
  }
}
