/* tslint:disable */
/* eslint-disable */
/**
 * WI API
 * API für Verwaltung von Personen, Dozenten, Studierenden, Forschungen, Modulen und Kursen
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __awaiter =
  (this && this.__awaiter) ||
  function (thisArg, _arguments, P, generator) {
    function adopt(value) {
      return value instanceof P
        ? value
        : new P(function (resolve) {
            resolve(value);
          });
    }
    return new (P || (P = Promise))(function (resolve, reject) {
      function fulfilled(value) {
        try {
          step(generator.next(value));
        } catch (e) {
          reject(e);
        }
      }
      function rejected(value) {
        try {
          step(generator["throw"](value));
        } catch (e) {
          reject(e);
        }
      }
      function step(result) {
        result.done
          ? resolve(result.value)
          : adopt(result.value).then(fulfilled, rejected);
      }
      step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
  };
import * as runtime from "../runtime.js";
import {
  GetLecturers200ResponseInnerFromJSON,
  GetSupervisors200ResponseInnerFromJSON,
  GetUser200ResponseFromJSON,
} from "../models/index.js";
/**
 *
 */
export class UserApi extends runtime.BaseAPI {
  /**
   * Liste aller dozenten
   */
  getLecturersRaw(initOverrides) {
    return __awaiter(this, void 0, void 0, function* () {
      const queryParameters = {};
      const headerParameters = {};
      if (this.configuration && this.configuration.apiKey) {
        queryParameters["key"] = yield this.configuration.apiKey("key"); // ApiKeyAuth authentication
      }
      let urlPath = `/lecturers`;
      const response = yield this.request(
        {
          path: urlPath,
          method: "GET",
          headers: headerParameters,
          query: queryParameters,
        },
        initOverrides,
      );
      return new runtime.JSONApiResponse(response, (jsonValue) =>
        jsonValue.map(GetLecturers200ResponseInnerFromJSON),
      );
    });
  }
  /**
   * Liste aller dozenten
   */
  getLecturers(initOverrides) {
    return __awaiter(this, void 0, void 0, function* () {
      const response = yield this.getLecturersRaw(initOverrides);
      return yield response.value();
    });
  }
  /**
   * Betreuer für jahr und einheit
   */
  getSupervisorsRaw(requestParameters, initOverrides) {
    return __awaiter(this, void 0, void 0, function* () {
      if (requestParameters["academicYear"] == null) {
        throw new runtime.RequiredError(
          "academicYear",
          'Required parameter "academicYear" was null or undefined when calling getSupervisors().',
        );
      }
      if (requestParameters["unitId"] == null) {
        throw new runtime.RequiredError(
          "unitId",
          'Required parameter "unitId" was null or undefined when calling getSupervisors().',
        );
      }
      const queryParameters = {};
      const headerParameters = {};
      if (this.configuration && this.configuration.apiKey) {
        queryParameters["key"] = yield this.configuration.apiKey("key"); // ApiKeyAuth authentication
      }
      let urlPath = `/supervisors/{academicYear}/{unitId}`;
      urlPath = urlPath.replace(
        `{${"academicYear"}}`,
        encodeURIComponent(String(requestParameters["academicYear"])),
      );
      urlPath = urlPath.replace(
        `{${"unitId"}}`,
        encodeURIComponent(String(requestParameters["unitId"])),
      );
      const response = yield this.request(
        {
          path: urlPath,
          method: "GET",
          headers: headerParameters,
          query: queryParameters,
        },
        initOverrides,
      );
      return new runtime.JSONApiResponse(response, (jsonValue) =>
        jsonValue.map(GetSupervisors200ResponseInnerFromJSON),
      );
    });
  }
  /**
   * Betreuer für jahr und einheit
   */
  getSupervisors(requestParameters, initOverrides) {
    return __awaiter(this, void 0, void 0, function* () {
      const response = yield this.getSupervisorsRaw(
        requestParameters,
        initOverrides,
      );
      return yield response.value();
    });
  }
  /**
   * Informationen des angemeldeten benutzers
   */
  getUserRaw(initOverrides) {
    return __awaiter(this, void 0, void 0, function* () {
      const queryParameters = {};
      const headerParameters = {};
      if (this.configuration && this.configuration.apiKey) {
        queryParameters["key"] = yield this.configuration.apiKey("key"); // ApiKeyAuth authentication
      }
      let urlPath = `/user`;
      const response = yield this.request(
        {
          path: urlPath,
          method: "GET",
          headers: headerParameters,
          query: queryParameters,
        },
        initOverrides,
      );
      return new runtime.JSONApiResponse(response, (jsonValue) =>
        GetUser200ResponseFromJSON(jsonValue),
      );
    });
  }
  /**
   * Informationen des angemeldeten benutzers
   */
  getUser(initOverrides) {
    return __awaiter(this, void 0, void 0, function* () {
      const response = yield this.getUserRaw(initOverrides);
      return yield response.value();
    });
  }
}
