/* tslint:disable */
/* eslint-disable */
/**
 * WI API
 * API für Verwaltung von Personen, Dozenten, Studierenden, Forschungen, Modulen und Kursen
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetCourses200ResponseInner
 */
export interface GetCourses200ResponseInner {
  /**
   *
   * @type {string}
   * @memberof GetCourses200ResponseInner
   */
  courseNr?: string;
  /**
   *
   * @type {string}
   * @memberof GetCourses200ResponseInner
   */
  yearName?: string;
  /**
   *
   * @type {string}
   * @memberof GetCourses200ResponseInner
   */
  studyfield?: string;
}

/**
 * Check if a given object implements the GetCourses200ResponseInner interface.
 */
export function instanceOfGetCourses200ResponseInner(
  value: object,
): value is GetCourses200ResponseInner {
  return true;
}

export function GetCourses200ResponseInnerFromJSON(
  json: any,
): GetCourses200ResponseInner {
  return GetCourses200ResponseInnerFromJSONTyped(json, false);
}

export function GetCourses200ResponseInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetCourses200ResponseInner {
  if (json == null) {
    return json;
  }
  return {
    courseNr: json["CourseNr"] == null ? undefined : json["CourseNr"],
    yearName: json["YearName"] == null ? undefined : json["YearName"],
    studyfield: json["Studyfield"] == null ? undefined : json["Studyfield"],
  };
}

export function GetCourses200ResponseInnerToJSON(
  json: any,
): GetCourses200ResponseInner {
  return GetCourses200ResponseInnerToJSONTyped(json, false);
}

export function GetCourses200ResponseInnerToJSONTyped(
  value?: GetCourses200ResponseInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    CourseNr: value["courseNr"],
    YearName: value["yearName"],
    Studyfield: value["studyfield"],
  };
}
