/* tslint:disable */
/* eslint-disable */
/**
 * WI API
 * API für Verwaltung von Personen, Dozenten, Studierenden, Forschungen, Modulen und Kursen
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetLecturers200ResponseInner
 */
export interface GetLecturers200ResponseInner {
  /**
   *
   * @type {number}
   * @memberof GetLecturers200ResponseInner
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof GetLecturers200ResponseInner
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof GetLecturers200ResponseInner
   */
  firstname?: string;
  /**
   *
   * @type {string}
   * @memberof GetLecturers200ResponseInner
   */
  lastname?: string;
  /**
   *
   * @type {string}
   * @memberof GetLecturers200ResponseInner
   */
  gender?: string;
  /**
   *
   * @type {string}
   * @memberof GetLecturers200ResponseInner
   */
  salutationShort?: string;
  /**
   *
   * @type {string}
   * @memberof GetLecturers200ResponseInner
   */
  salutationFull?: string;
  /**
   *
   * @type {string}
   * @memberof GetLecturers200ResponseInner
   */
  roleNow?: string;
  /**
   *
   * @type {number}
   * @memberof GetLecturers200ResponseInner
   */
  personnelId?: number;
}

/**
 * Check if a given object implements the GetLecturers200ResponseInner interface.
 */
export function instanceOfGetLecturers200ResponseInner(
  value: object,
): value is GetLecturers200ResponseInner {
  return true;
}

export function GetLecturers200ResponseInnerFromJSON(
  json: any,
): GetLecturers200ResponseInner {
  return GetLecturers200ResponseInnerFromJSONTyped(json, false);
}

export function GetLecturers200ResponseInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetLecturers200ResponseInner {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    title: json["Title"] == null ? undefined : json["Title"],
    firstname: json["Firstname"] == null ? undefined : json["Firstname"],
    lastname: json["Lastname"] == null ? undefined : json["Lastname"],
    gender: json["Gender"] == null ? undefined : json["Gender"],
    salutationShort:
      json["Salutation_short"] == null ? undefined : json["Salutation_short"],
    salutationFull:
      json["Salutation_full"] == null ? undefined : json["Salutation_full"],
    roleNow: json["RoleNow"] == null ? undefined : json["RoleNow"],
    personnelId: json["PersonnelId"] == null ? undefined : json["PersonnelId"],
  };
}

export function GetLecturers200ResponseInnerToJSON(
  json: any,
): GetLecturers200ResponseInner {
  return GetLecturers200ResponseInnerToJSONTyped(json, false);
}

export function GetLecturers200ResponseInnerToJSONTyped(
  value?: GetLecturers200ResponseInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    Title: value["title"],
    Firstname: value["firstname"],
    Lastname: value["lastname"],
    Gender: value["gender"],
    Salutation_short: value["salutationShort"],
    Salutation_full: value["salutationFull"],
    RoleNow: value["roleNow"],
    PersonnelId: value["personnelId"],
  };
}
