/* tslint:disable */
/* eslint-disable */
/**
 * WI API
 * API für Verwaltung von Personen, Dozenten, Studierenden, Forschungen, Modulen und Kursen
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetResearchMathWished200ResponseInner
 */
export interface GetResearchMathWished200ResponseInner {
  /**
   *
   * @type {number}
   * @memberof GetResearchMathWished200ResponseInner
   */
  researchId?: number;
  /**
   *
   * @type {string}
   * @memberof GetResearchMathWished200ResponseInner
   */
  matchWishLast?: string;
  /**
   *
   * @type {string}
   * @memberof GetResearchMathWished200ResponseInner
   */
  matchWishFirst?: string;
  /**
   *
   * @type {number}
   * @memberof GetResearchMathWished200ResponseInner
   */
  matchWishId?: number;
  /**
   *
   * @type {number}
   * @memberof GetResearchMathWished200ResponseInner
   */
  personFromId?: number;
  /**
   *
   * @type {number}
   * @memberof GetResearchMathWished200ResponseInner
   */
  personnelWhoId?: number;
  /**
   *
   * @type {number}
   * @memberof GetResearchMathWished200ResponseInner
   */
  priority?: number;
  /**
   *
   * @type {number}
   * @memberof GetResearchMathWished200ResponseInner
   */
  _true?: number;
  /**
   *
   * @type {string}
   * @memberof GetResearchMathWished200ResponseInner
   */
  matchWisherLast?: string;
  /**
   *
   * @type {string}
   * @memberof GetResearchMathWished200ResponseInner
   */
  matchWisherFirst?: string;
}

/**
 * Check if a given object implements the GetResearchMathWished200ResponseInner interface.
 */
export function instanceOfGetResearchMathWished200ResponseInner(
  value: object,
): value is GetResearchMathWished200ResponseInner {
  return true;
}

export function GetResearchMathWished200ResponseInnerFromJSON(
  json: any,
): GetResearchMathWished200ResponseInner {
  return GetResearchMathWished200ResponseInnerFromJSONTyped(json, false);
}

export function GetResearchMathWished200ResponseInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetResearchMathWished200ResponseInner {
  if (json == null) {
    return json;
  }
  return {
    researchId: json["ResearchId"] == null ? undefined : json["ResearchId"],
    matchWishLast:
      json["MatchWishLast"] == null ? undefined : json["MatchWishLast"],
    matchWishFirst:
      json["MatchWishFirst"] == null ? undefined : json["MatchWishFirst"],
    matchWishId: json["MatchWishId"] == null ? undefined : json["MatchWishId"],
    personFromId:
      json["PersonFromId"] == null ? undefined : json["PersonFromId"],
    personnelWhoId:
      json["PersonnelWhoId"] == null ? undefined : json["PersonnelWhoId"],
    priority: json["Priority"] == null ? undefined : json["Priority"],
    _true: json["true"] == null ? undefined : json["true"],
    matchWisherLast:
      json["MatchWisherLast"] == null ? undefined : json["MatchWisherLast"],
    matchWisherFirst:
      json["MatchWisherFirst"] == null ? undefined : json["MatchWisherFirst"],
  };
}

export function GetResearchMathWished200ResponseInnerToJSON(
  json: any,
): GetResearchMathWished200ResponseInner {
  return GetResearchMathWished200ResponseInnerToJSONTyped(json, false);
}

export function GetResearchMathWished200ResponseInnerToJSONTyped(
  value?: GetResearchMathWished200ResponseInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    ResearchId: value["researchId"],
    MatchWishLast: value["matchWishLast"],
    MatchWishFirst: value["matchWishFirst"],
    MatchWishId: value["matchWishId"],
    PersonFromId: value["personFromId"],
    PersonnelWhoId: value["personnelWhoId"],
    Priority: value["priority"],
    true: value["_true"],
    MatchWisherLast: value["matchWisherLast"],
    MatchWisherFirst: value["matchWisherFirst"],
  };
}
