/* tslint:disable */
/* eslint-disable */
/**
 * WI API
 * API für Verwaltung von Personen, Dozenten, Studierenden, Forschungen, Modulen und Kursen
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetResearches200ResponseInner
 */
export interface GetResearches200ResponseInner {
  /**
   *
   * @type {number}
   * @memberof GetResearches200ResponseInner
   */
  researchId?: number;
  /**
   *
   * @type {string}
   * @memberof GetResearches200ResponseInner
   */
  title?: string;
  /**
   *
   * @type {number}
   * @memberof GetResearches200ResponseInner
   */
  personnelId?: number;
  /**
   *
   * @type {string}
   * @memberof GetResearches200ResponseInner
   */
  unitName?: string;
  /**
   *
   * @type {number}
   * @memberof GetResearches200ResponseInner
   */
  matriNr?: number;
  /**
   *
   * @type {number}
   * @memberof GetResearches200ResponseInner
   */
  studentPersonId?: number;
  /**
   *
   * @type {string}
   * @memberof GetResearches200ResponseInner
   */
  studentFirst?: string;
  /**
   *
   * @type {string}
   * @memberof GetResearches200ResponseInner
   */
  studentLast?: string;
  /**
   *
   * @type {string}
   * @memberof GetResearches200ResponseInner
   */
  courseNr?: string;
  /**
   *
   * @type {string}
   * @memberof GetResearches200ResponseInner
   */
  problem?: string;
  /**
   *
   * @type {string}
   * @memberof GetResearches200ResponseInner
   */
  methodology?: string;
  /**
   *
   * @type {string}
   * @memberof GetResearches200ResponseInner
   */
  goal?: string;
}

/**
 * Check if a given object implements the GetResearches200ResponseInner interface.
 */
export function instanceOfGetResearches200ResponseInner(
  value: object,
): value is GetResearches200ResponseInner {
  return true;
}

export function GetResearches200ResponseInnerFromJSON(
  json: any,
): GetResearches200ResponseInner {
  return GetResearches200ResponseInnerFromJSONTyped(json, false);
}

export function GetResearches200ResponseInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetResearches200ResponseInner {
  if (json == null) {
    return json;
  }
  return {
    researchId: json["ResearchId"] == null ? undefined : json["ResearchId"],
    title: json["Title"] == null ? undefined : json["Title"],
    personnelId: json["PersonnelId"] == null ? undefined : json["PersonnelId"],
    unitName: json["UnitName"] == null ? undefined : json["UnitName"],
    matriNr: json["MatriNr"] == null ? undefined : json["MatriNr"],
    studentPersonId:
      json["StudentPersonId"] == null ? undefined : json["StudentPersonId"],
    studentFirst:
      json["StudentFirst"] == null ? undefined : json["StudentFirst"],
    studentLast: json["StudentLast"] == null ? undefined : json["StudentLast"],
    courseNr: json["CourseNr"] == null ? undefined : json["CourseNr"],
    problem: json["Problem"] == null ? undefined : json["Problem"],
    methodology: json["Methodology"] == null ? undefined : json["Methodology"],
    goal: json["Goal"] == null ? undefined : json["Goal"],
  };
}

export function GetResearches200ResponseInnerToJSON(
  json: any,
): GetResearches200ResponseInner {
  return GetResearches200ResponseInnerToJSONTyped(json, false);
}

export function GetResearches200ResponseInnerToJSONTyped(
  value?: GetResearches200ResponseInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    ResearchId: value["researchId"],
    Title: value["title"],
    PersonnelId: value["personnelId"],
    UnitName: value["unitName"],
    MatriNr: value["matriNr"],
    StudentPersonId: value["studentPersonId"],
    StudentFirst: value["studentFirst"],
    StudentLast: value["studentLast"],
    CourseNr: value["courseNr"],
    Problem: value["problem"],
    Methodology: value["methodology"],
    Goal: value["goal"],
  };
}
