/* tslint:disable */
/* eslint-disable */
/**
 * WI API
 * API für Verwaltung von Personen, Dozenten, Studierenden, Forschungen, Modulen und Kursen
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetSupervisors200ResponseInner
 */
export interface GetSupervisors200ResponseInner {
  /**
   *
   * @type {number}
   * @memberof GetSupervisors200ResponseInner
   */
  personnelId?: number;
  /**
   *
   * @type {string}
   * @memberof GetSupervisors200ResponseInner
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof GetSupervisors200ResponseInner
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof GetSupervisors200ResponseInner
   */
  firstname?: string;
  /**
   *
   * @type {string}
   * @memberof GetSupervisors200ResponseInner
   */
  lastname?: string;
  /**
   *
   * @type {number}
   * @memberof GetSupervisors200ResponseInner
   */
  max?: number;
  /**
   *
   * @type {number}
   * @memberof GetSupervisors200ResponseInner
   */
  randomSel?: number;
  /**
   *
   * @type {string}
   * @memberof GetSupervisors200ResponseInner
   */
  comment?: string;
  /**
   *
   * @type {number}
   * @memberof GetSupervisors200ResponseInner
   */
  unitId?: number;
  /**
   *
   * @type {number}
   * @memberof GetSupervisors200ResponseInner
   */
  cMatch?: number;
}

/**
 * Check if a given object implements the GetSupervisors200ResponseInner interface.
 */
export function instanceOfGetSupervisors200ResponseInner(
  value: object,
): value is GetSupervisors200ResponseInner {
  return true;
}

export function GetSupervisors200ResponseInnerFromJSON(
  json: any,
): GetSupervisors200ResponseInner {
  return GetSupervisors200ResponseInnerFromJSONTyped(json, false);
}

export function GetSupervisors200ResponseInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetSupervisors200ResponseInner {
  if (json == null) {
    return json;
  }
  return {
    personnelId: json["PersonnelId"] == null ? undefined : json["PersonnelId"],
    name: json["Name"] == null ? undefined : json["Name"],
    title: json["Title"] == null ? undefined : json["Title"],
    firstname: json["Firstname"] == null ? undefined : json["Firstname"],
    lastname: json["Lastname"] == null ? undefined : json["Lastname"],
    max: json["Max"] == null ? undefined : json["Max"],
    randomSel: json["RandomSel"] == null ? undefined : json["RandomSel"],
    comment: json["Comment"] == null ? undefined : json["Comment"],
    unitId: json["UnitId"] == null ? undefined : json["UnitId"],
    cMatch: json["CMatch"] == null ? undefined : json["CMatch"],
  };
}

export function GetSupervisors200ResponseInnerToJSON(
  json: any,
): GetSupervisors200ResponseInner {
  return GetSupervisors200ResponseInnerToJSONTyped(json, false);
}

export function GetSupervisors200ResponseInnerToJSONTyped(
  value?: GetSupervisors200ResponseInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    PersonnelId: value["personnelId"],
    Name: value["name"],
    Title: value["title"],
    Firstname: value["firstname"],
    Lastname: value["lastname"],
    Max: value["max"],
    RandomSel: value["randomSel"],
    Comment: value["comment"],
    UnitId: value["unitId"],
    CMatch: value["cMatch"],
  };
}
