/* tslint:disable */
/* eslint-disable */
/**
 * WI API
 * API für Verwaltung von Personen, Dozenten, Studierenden, Forschungen, Modulen und Kursen
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetUser200Response
 */
export interface GetUser200Response {
  /**
   *
   * @type {number}
   * @memberof GetUser200Response
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof GetUser200Response
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof GetUser200Response
   */
  firstname?: string;
  /**
   *
   * @type {string}
   * @memberof GetUser200Response
   */
  lastname?: string;
  /**
   *
   * @type {string}
   * @memberof GetUser200Response
   */
  gender?: string;
  /**
   *
   * @type {string}
   * @memberof GetUser200Response
   */
  salutationShort?: string;
  /**
   *
   * @type {string}
   * @memberof GetUser200Response
   */
  salutationFull?: string;
  /**
   *
   * @type {string}
   * @memberof GetUser200Response
   */
  roleNow?: string;
  /**
   *
   * @type {number}
   * @memberof GetUser200Response
   */
  personnelId?: number;
  /**
   *
   * @type {number}
   * @memberof GetUser200Response
   */
  matriNr?: number;
  /**
   *
   * @type {number}
   * @memberof GetUser200Response
   */
  courseId?: number;
  /**
   *
   * @type {number}
   * @memberof GetUser200Response
   */
  fieldId?: number;
}

/**
 * Check if a given object implements the GetUser200Response interface.
 */
export function instanceOfGetUser200Response(
  value: object,
): value is GetUser200Response {
  return true;
}

export function GetUser200ResponseFromJSON(json: any): GetUser200Response {
  return GetUser200ResponseFromJSONTyped(json, false);
}

export function GetUser200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetUser200Response {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    title: json["Title"] == null ? undefined : json["Title"],
    firstname: json["Firstname"] == null ? undefined : json["Firstname"],
    lastname: json["Lastname"] == null ? undefined : json["Lastname"],
    gender: json["Gender"] == null ? undefined : json["Gender"],
    salutationShort:
      json["Salutation_short"] == null ? undefined : json["Salutation_short"],
    salutationFull:
      json["Salutation_full"] == null ? undefined : json["Salutation_full"],
    roleNow: json["RoleNow"] == null ? undefined : json["RoleNow"],
    personnelId: json["PersonnelId"] == null ? undefined : json["PersonnelId"],
    matriNr: json["MatriNr"] == null ? undefined : json["MatriNr"],
    courseId: json["CourseId"] == null ? undefined : json["CourseId"],
    fieldId: json["FieldId"] == null ? undefined : json["FieldId"],
  };
}

export function GetUser200ResponseToJSON(json: any): GetUser200Response {
  return GetUser200ResponseToJSONTyped(json, false);
}

export function GetUser200ResponseToJSONTyped(
  value?: GetUser200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    Title: value["title"],
    Firstname: value["firstname"],
    Lastname: value["lastname"],
    Gender: value["gender"],
    Salutation_short: value["salutationShort"],
    Salutation_full: value["salutationFull"],
    RoleNow: value["roleNow"],
    PersonnelId: value["personnelId"],
    MatriNr: value["matriNr"],
    CourseId: value["courseId"],
    FieldId: value["fieldId"],
  };
}
