/* tslint:disable */
/* eslint-disable */
/**
 * WI API
 * API für Verwaltung von Personen, Dozenten, Studierenden, Forschungen, Modulen und Kursen
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  GetCourses200ResponseInner,
  GetModuleLecturers200ResponseInner,
  GetModuleUnits200ResponseInner,
  GetResearchMathWished200ResponseInner,
  GetResearches200ResponseInner,
} from "../models/index";
import {
  GetCourses200ResponseInnerFromJSON,
  GetCourses200ResponseInnerToJSON,
  GetModuleLecturers200ResponseInnerFromJSON,
  GetModuleLecturers200ResponseInnerToJSON,
  GetModuleUnits200ResponseInnerFromJSON,
  GetModuleUnits200ResponseInnerToJSON,
  GetResearchMathWished200ResponseInnerFromJSON,
  GetResearchMathWished200ResponseInnerToJSON,
  GetResearches200ResponseInnerFromJSON,
  GetResearches200ResponseInnerToJSON,
} from "../models/index";

export interface GetCoursesRequest {
  date: Date;
}

export interface GetResearchMathWishedRequest {
  researchId: number;
}

export interface GetResearchesRequest {
  date: Date;
}

/**
 *
 */
export class LecturesApi extends runtime.BaseAPI {
  /**
   * Liste der kurse zu einem datum
   */
  async getCoursesRaw(
    requestParameters: GetCoursesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<GetCourses200ResponseInner>>> {
    if (requestParameters["date"] == null) {
      throw new runtime.RequiredError(
        "date",
        'Required parameter "date" was null or undefined when calling getCourses().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      queryParameters["key"] = await this.configuration.apiKey("key"); // ApiKeyAuth authentication
    }

    let urlPath = `/courses/{date}`;
    if (requestParameters["date"] instanceof Date) {
      urlPath = urlPath.replace(
        `{${"date"}}`,
        encodeURIComponent(
          requestParameters["date"].toISOString().substring(0, 10),
        ),
      );
    } else {
      urlPath = urlPath.replace(
        `{${"date"}}`,
        encodeURIComponent(String(requestParameters["date"])),
      );
    }

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(GetCourses200ResponseInnerFromJSON),
    );
  }

  /**
   * Liste der kurse zu einem datum
   */
  async getCourses(
    requestParameters: GetCoursesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<GetCourses200ResponseInner>> {
    const response = await this.getCoursesRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Dozenten zu moduleinheiten
   */
  async getModuleLecturersRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<GetModuleLecturers200ResponseInner>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      queryParameters["key"] = await this.configuration.apiKey("key"); // ApiKeyAuth authentication
    }

    let urlPath = `/module_lecturer`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(GetModuleLecturers200ResponseInnerFromJSON),
    );
  }

  /**
   * Dozenten zu moduleinheiten
   */
  async getModuleLecturers(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<GetModuleLecturers200ResponseInner>> {
    const response = await this.getModuleLecturersRaw(initOverrides);
    return await response.value();
  }

  /**
   * Liste der moduleinheiten
   */
  async getModuleUnitsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<GetModuleUnits200ResponseInner>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      queryParameters["key"] = await this.configuration.apiKey("key"); // ApiKeyAuth authentication
    }

    let urlPath = `/module_units`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(GetModuleUnits200ResponseInnerFromJSON),
    );
  }

  /**
   * Liste der moduleinheiten
   */
  async getModuleUnits(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<GetModuleUnits200ResponseInner>> {
    const response = await this.getModuleUnitsRaw(initOverrides);
    return await response.value();
  }

  /**
   * Matchwishes für eine forschung
   */
  async getResearchMathWishedRaw(
    requestParameters: GetResearchMathWishedRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<
    runtime.ApiResponse<Array<GetResearchMathWished200ResponseInner>>
  > {
    if (requestParameters["researchId"] == null) {
      throw new runtime.RequiredError(
        "researchId",
        'Required parameter "researchId" was null or undefined when calling getResearchMathWished().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      queryParameters["key"] = await this.configuration.apiKey("key"); // ApiKeyAuth authentication
    }

    let urlPath = `/research-matchwishes/{researchId}`;
    urlPath = urlPath.replace(
      `{${"researchId"}}`,
      encodeURIComponent(String(requestParameters["researchId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(GetResearchMathWished200ResponseInnerFromJSON),
    );
  }

  /**
   * Matchwishes für eine forschung
   */
  async getResearchMathWished(
    requestParameters: GetResearchMathWishedRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<GetResearchMathWished200ResponseInner>> {
    const response = await this.getResearchMathWishedRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Forschungen ab einem datum
   */
  async getResearchesRaw(
    requestParameters: GetResearchesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<GetResearches200ResponseInner>>> {
    if (requestParameters["date"] == null) {
      throw new runtime.RequiredError(
        "date",
        'Required parameter "date" was null or undefined when calling getResearches().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      queryParameters["key"] = await this.configuration.apiKey("key"); // ApiKeyAuth authentication
    }

    let urlPath = `/researches/{date}`;
    if (requestParameters["date"] instanceof Date) {
      urlPath = urlPath.replace(
        `{${"date"}}`,
        encodeURIComponent(
          requestParameters["date"].toISOString().substring(0, 10),
        ),
      );
    } else {
      urlPath = urlPath.replace(
        `{${"date"}}`,
        encodeURIComponent(String(requestParameters["date"])),
      );
    }

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(GetResearches200ResponseInnerFromJSON),
    );
  }

  /**
   * Forschungen ab einem datum
   */
  async getResearches(
    requestParameters: GetResearchesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<GetResearches200ResponseInner>> {
    const response = await this.getResearchesRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
