/* tslint:disable */
/* eslint-disable */
/**
 * WI API
 * API für Verwaltung von Personen, Dozenten, Studierenden, Forschungen, Modulen und Kursen
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { GetSemester200ResponseInner } from "../models/index";
import {
  GetSemester200ResponseInnerFromJSON,
  GetSemester200ResponseInnerToJSON,
} from "../models/index";

/**
 *
 */
export class SemesterApi extends runtime.BaseAPI {
  /**
   * Liste aller semester
   */
  async getSemesterRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<GetSemester200ResponseInner>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      queryParameters["key"] = await this.configuration.apiKey("key"); // ApiKeyAuth authentication
    }

    let urlPath = `/semester`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(GetSemester200ResponseInnerFromJSON),
    );
  }

  /**
   * Liste aller semester
   */
  async getSemester(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<GetSemester200ResponseInner>> {
    const response = await this.getSemesterRaw(initOverrides);
    return await response.value();
  }
}
