/* tslint:disable */
/* eslint-disable */
/**
 * WI API
 * API für Verwaltung von Personen, Dozenten, Studierenden, Forschungen, Modulen und Kursen
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  GetLecturers200ResponseInner,
  GetSupervisors200ResponseInner,
  GetUser200Response,
} from "../models/index";
import {
  GetLecturers200ResponseInnerFromJSON,
  GetLecturers200ResponseInnerToJSON,
  GetSupervisors200ResponseInnerFromJSON,
  GetSupervisors200ResponseInnerToJSON,
  GetUser200ResponseFromJSON,
  GetUser200ResponseToJSON,
} from "../models/index";

export interface GetSupervisorsRequest {
  academicYear: number;
  unitId: number;
}

/**
 *
 */
export class UserApi extends runtime.BaseAPI {
  /**
   * Liste aller dozenten
   */
  async getLecturersRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<GetLecturers200ResponseInner>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      queryParameters["key"] = await this.configuration.apiKey("key"); // ApiKeyAuth authentication
    }

    let urlPath = `/lecturers`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(GetLecturers200ResponseInnerFromJSON),
    );
  }

  /**
   * Liste aller dozenten
   */
  async getLecturers(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<GetLecturers200ResponseInner>> {
    const response = await this.getLecturersRaw(initOverrides);
    return await response.value();
  }

  /**
   * Betreuer für jahr und einheit
   */
  async getSupervisorsRaw(
    requestParameters: GetSupervisorsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<GetSupervisors200ResponseInner>>> {
    if (requestParameters["academicYear"] == null) {
      throw new runtime.RequiredError(
        "academicYear",
        'Required parameter "academicYear" was null or undefined when calling getSupervisors().',
      );
    }

    if (requestParameters["unitId"] == null) {
      throw new runtime.RequiredError(
        "unitId",
        'Required parameter "unitId" was null or undefined when calling getSupervisors().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      queryParameters["key"] = await this.configuration.apiKey("key"); // ApiKeyAuth authentication
    }

    let urlPath = `/supervisors/{academicYear}/{unitId}`;
    urlPath = urlPath.replace(
      `{${"academicYear"}}`,
      encodeURIComponent(String(requestParameters["academicYear"])),
    );
    urlPath = urlPath.replace(
      `{${"unitId"}}`,
      encodeURIComponent(String(requestParameters["unitId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(GetSupervisors200ResponseInnerFromJSON),
    );
  }

  /**
   * Betreuer für jahr und einheit
   */
  async getSupervisors(
    requestParameters: GetSupervisorsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<GetSupervisors200ResponseInner>> {
    const response = await this.getSupervisorsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Informationen des angemeldeten benutzers
   */
  async getUserRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetUser200Response>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      queryParameters["key"] = await this.configuration.apiKey("key"); // ApiKeyAuth authentication
    }

    let urlPath = `/user`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetUser200ResponseFromJSON(jsonValue),
    );
  }

  /**
   * Informationen des angemeldeten benutzers
   */
  async getUser(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetUser200Response> {
    const response = await this.getUserRaw(initOverrides);
    return await response.value();
  }
}
